name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to release'
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        env:
          PYTHONPATH: .
        run: uv run pytest -q

      - name: Update version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml
          sed -i "s/^__version__ = \".*\"/__version__ = \"${VERSION}\"/" tide/__init__.py
          sed -i "s/version=\".*\"/version=\"${VERSION}\",/" setup.py

      - name: Commit and tag
        env:
          VERSION: ${{ inputs.version }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add pyproject.toml tide/__init__.py setup.py
          git commit -m "Bump version to ${VERSION}"
          git tag "v${VERSION}"

      - name: Push changes and tag
        env:
          VERSION: ${{ inputs.version }}
        run: |
          git push origin HEAD:main
          git push origin "v${VERSION}"
